### ISSUE TITLE
does not show images when root component re-renders

### ISSUE THREAD

**Issue by nitruxa** [loktar00/react-lazy-load#52]
When children component is already rendered, but root component re-renders (for instance filtering table rows) and `LazyLoad` component becomes visible, it does not check if it is `inViewport` or not, so images does not show up, until you scroll or resize (sometimes when filtering your scroll bar disappears, as content is really small :smile:)

easy fix, which I tried, would be calling `lazyLoadHandler` inside `componentWillReceiveProps` function.

**Comment by nitruxa** [comment]
Серега, я в тебя верю... :+1: :wink:

**Comment by sejoker** [comment]
I agree with @nitruxa. This is a regression bug introduced in version 3. In version 2 of the component, we had `componentDidUpdate` which called the analog of `lazyLoadHandler`. On the other hand in the latest version, `shouldComponentUpdate` handler was introduced. The solution @nitruxa suggests actually will work because `componentWillReceiveProps` is invoked before `shouldComponentUpdate` and if `inViewport` returns `true` will call `setState({visible: true})`.

**Comment by sergeylaptev** [comment]
It makes sense. I'll play with it;) Need to make sure, that we can do it without crucial speed regression.

**Comment by sergeylaptev** [comment]
3.0.10 is in npm. Please check this out and notify me about results

**Comment by sejoker** [comment]
@sergeylaptev thanks, will test 3.0.10 on our codebase soon.

**Comment by fredcorn** [comment]
Thanks~ This version fixed my issue. Appreciate this job.

**Comment by sejoker** [comment]
@sergeylaptev it works perfectly, I am going to migrate to the latest version in production

**Comment by sergeylaptev** [comment]
@sejoker glad to hear:)

**Comment by nitruxa** [comment]
good job. thanks 👍
